service: aws-gh-prs
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: java8
  memorySize: 384

package:
  artifact: target/scala-2.12/aws-gh-prs-assembly-0.6.0-SNAPSHOT.jar

functions:
  webhook:
    handler: prs.Main::handleRequest
    timeout: 240
    events:
      - http:
          path: /webhook
          method: post
