name: build

on: [push]

jobs:
  sbt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
        cache: 'sbt'
    - run: sbt assembly
    - uses: actions/upload-artifact@v3
      with:
        name: aws-gh-prs-assembly-0.6.0-SNAPSHOT
        path: target/scala-2.12/aws-gh-prs-assembly-0.6.0-SNAPSHOT.jar
        retention-days: 2

  npm:

    runs-on: ubuntu-latest

    needs: [sbt]
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: aws-gh-prs-assembly-0.6.0-SNAPSHOT
    - run: mkdir -p ./target/scala-2.12
    - run: mv ./aws-gh-prs-assembly-0.6.0-SNAPSHOT.jar ./target/scala-2.12
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npx sls package
