name: npm

on:
  workflow_run:
    workflows: [sbt]
    types: [completed]

jobs:
  npm:

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: 'Fat JAR file'
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npx sls package
