name: sbt

on: [push]

jobs:
  sbt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
        cache: 'sbt'
    - run: sbt assembly
    - uses: actions/upload-artifact@v3
      with:
        name: 'Fat JAR file'
        path: target/scala-2.*/aws-gh-prs-assembly-*-SNAPSHOT.jar
        retention-days: 2
